### ISSUE TITLE
Add a citation file

### ISSUE THREAD

**Issue by bakhtos** [EvoTestOps/LogLead#27]
We can add a citation file for the BibTex to appear in the repo description

See here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by mmantyla** [comment]
Yes! We recommend citing the paper, but we would need to republish it with new names :-D. Therefore, I think switching the citing to the repository is the most appropriate and easiest way. Your name should definitely be included as well.

**Comment by mmantyla** [comment]
In terms of Google Scholar, a repo is most likely a citable item. However, for Scopus, it is doubtful. This means that this repo will not appear in our personal Scopus profiles. It might be significant for those of us with career ambitions.
