### ISSUE TITLE
Refactor loglead files to folders

### ISSUE THREAD

**Issue by mmantyla** [EvoTestOps/LogLead#5]
loader.py, enhancers.py, and anomaly_detection.py to folders loaders, enhancers, anomaly_detectors and separate these big files to separate files.

**Comment by mmantyla** [comment]
Loaders refactored.

**Comment by bakhtos** [comment]
Working on this now:
- [x] Enhancers refactored
- How should `anomaly_detection.py` be refactored? Now it only has one 'public' class `AnomalyDetection` with many `train_` methods.
